In [65]:
import numpy as np


In [66]:
# CREATING AN ARRAY
arr = np.array ([1,2,3,4])
print (arr)
print (type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [67]:
# CREATING MULTI DIMENSIONAL ARRAY
a = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (a)
print (type(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [68]:
# SLICING IN SINGLE DIMENSION ARRAY
a = np.array ([1,2,3,4])
print (a[:])
print (a[0:2])
print (a[2:])

[1 2 3 4]
[1 2]
[3 4]


In [69]:
# SLICING IN MULTI DIMENSIONAL ARRAY
b = np.array ([[1,2,3,4],[5,6,7,8],[0,1,2,9]])
print (b[0:2,0:2])
print (b[0:2,0:3])
print (b[0,1:2])
print (b[1,1:3])
print (b[2,3])

[[1 2]
 [5 6]]
[[1 2 3]
 [5 6 7]]
[2]
[6 7]
9


In [70]:
# ATTRIBUTES OF ARRAY
c = np.array ([[1,2,3,4],[5,6,7,8],[0,1,2,9]])
print (np.shape(c)) # no. of rows and coloumns
print (np.size(c)) # total no. of elements
print (np.ndim(c)) # no. of dimensions
print (c.dtype) # datatype of stored elements 

(3, 4)
12
2
int64


In [71]:
#  INSPECTION OF ARRAY
a = [[10,20.4,3,60],[12,45.6,23,55]]
arr1 = np.array (a)
print (arr1.shape) # no. of rows and columns
print (len(arr1)) # no. of nested elements
print (np.size(arr1)) # total no. of elements
print (type(arr1)) # datatype of variable
print (arr1.dtype)
print (arr1.astype(int))
print (arr1.astype(str))

(2, 4)
2
8
<class 'numpy.ndarray'>
float64
[[10 20  3 60]
 [12 45 23 55]]
[['10.0' '20.4' '3.0' '60.0']
 ['12.0' '45.6' '23.0' '55.0']]


In [72]:
#  OPERATION AND FUNCTION
a1 = np.array ([10,20,30,40])
a2 = np.array ([1,2,3,4])

a3 = np.array ([[10,20],[30,40]])
a4 = np.array ([[1,2],[3,4]])

a5 = np.array ([2])
a6 = np.array ([1,4,9,16])
# ADDITION
print (a1+a2)
print (np.add(a1,a2))
print (a3+a4)
print (np.add(a3,a4))
#SUBTRACTION
print (a1-a2)
print (np.subtract(a1,a2))
print (a3-a4)
print (np.subtract(a3,a4))
#MULTIPLICATION
print (a1*a2)
print (np.multiply(a1,a2))
print (a3*a4)
print (np.multiply(a3,a4))
#DIVISION
print (a1/a2)
print (np.divide(a1,a2))
print (a3/a4)
print (np.divide(a3,a4).astype(int))
#POWER
p = print (np.power(a2,a5))
print (p)
print (a2**2)
#SQUARE ROOT
print (np.sqrt(a6).astype(int))




[11 22 33 44]
[11 22 33 44]
[[11 22]
 [33 44]]
[[11 22]
 [33 44]]
[ 9 18 27 36]
[ 9 18 27 36]
[[ 9 18]
 [27 36]]
[[ 9 18]
 [27 36]]
[ 10  40  90 160]
[ 10  40  90 160]
[[ 10  40]
 [ 90 160]]
[[ 10  40]
 [ 90 160]]
[10. 10. 10. 10.]
[10. 10. 10. 10.]
[[10. 10.]
 [10. 10.]]
[[10 10]
 [10 10]]
[ 1  4  9 16]
None
[ 1  4  9 16]
[1 2 3 4]


In [73]:
# CONCATENATION
a1 = np.array ([[1,2],[3,4]])
a2 = np.array ([[6,7],[8,9]])
# VERTICAL
print (np.concatenate([a1,a2]))
print (np.vstack([a1,a2]))
print (np.concatenate([a1,a2],axis = 0))
# # HORIZONTAL
print (np.hstack([a1,a2]))
print (np.concatenate([a1,a2],axis = 1))


[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[1 2 6 7]
 [3 4 8 9]]
[[1 2 6 7]
 [3 4 8 9]]


In [74]:
#  SPLITTING
a5 = np.array ([1,2,3,4,5])
s = np.array_split(a5,7)
t = np.array_split(a5,5)
u = np.array_split(a5,3)
# print (s)
# print (t)
# print (u)
a6 = np.array ([[1,2],[3,4]])
w= np.array_split(a6,4)
x = np.array_split(a6,3)
y = np.array_split(a6,2)
z = np.array_split(a6,1)
print (w)
print (x)
print (y)
print (z)




[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]
[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int64)]
[array([[1, 2]]), array([[3, 4]])]
[array([[1, 2],
       [3, 4]])]


In [75]:
# INSERT AND REMOVE ELEMENT
# APPEND
a = np.array ([1,2,3,4,5])
print (np.append(a,[6,7,8]))
# INSERT
print (np.insert(a,1,0))
print (np.insert(a,3,9))
# REMOVE
print (np.delete(a,1))



[1 2 3 4 5 6 7 8]
[1 0 2 3 4 5]
[1 2 3 9 4 5]
[1 3 4 5]


In [76]:
# SORT , SEARCH AND FILTER
# SORT
A = np.array ([1,3245,13,768,2])
B = np.sort(A)
print (B)
# SEARCH
S = np.where(A==1)
print (S)
# SEARCHSORT
ss = np.searchsorted(B,13)
print (ss)
# FILTER
F = [True,False,False,True,True]
N = A[F]
print (N)
T=  (A%2==0)
W = A[T]
print (W)

[   1    2   13  768 3245]
(array([0]),)
2
[  1 768   2]
[768   2]


In [77]:
#  AGGREGATING FUNCTION
G = np.array ([1,2,3])
print (np.sum(G))
print (np.min(G))
print (np.max(G))
print (np.cumsum(G))
print (np.cumprod(G))


6
1
3
[1 3 6]
[1 2 6]


In [78]:
#  AGGREGATING FUNCTION ON MULTI_DIMENSIONAL ARRAY
price= np.array ([100,100,150,200])
quantity= np.array([2,4,3,5])
tp= np.cumprod([price,quantity],axis = 0)
total = np.sum(tp)
print (total)


2600


In [79]:
#  STATISTICAL FUNCTION
import statistics as stats
a = np.array ([3,1,2,9,3,0,4,7,2,5,8,6])
print (np.mean(a))
print (np.median(a))
print (stats.mode(a))
print (np.std(a))
print (np.var(a))



4.166666666666667
3.5
3
2.733536577809454
7.472222222222222


In [80]:
# COOFICIENT OF CO_RELATION
a = [1,2,3,2,1]
b = [3,5,7,5,3]
c = [7,5,3,5,7]
d = [111,55,15,4,68324]
print (np.corrcoef([a,b]))
print (np.corrcoef([a,c]))
print (np.corrcoef([a,d]))


[[1. 1.]
 [1. 1.]]
[[ 1. -1.]
 [-1.  1.]]
[[ 1.         -0.53546142]
 [-0.53546142  1.        ]]
